"""Project Tamil Nadu district GeoJSON to static SVG path data (run once at dev time)."""
import json, math, sys
src, out = sys.argv[1], sys.argv[2]
d = json.load(open(src))
W, H, PAD = 560, 640, 16
lat0 = 11.0
k = math.cos(math.radians(lat0))
def rings(g):
    if g['type'] == 'Polygon': return [g['coordinates'][0]]
    return [p[0] for p in g['coordinates']]
allpts = [pt for f in d['features'] for r in rings(f['geometry']) for pt in r]
xs = [p[0]*k for p in allpts]; ys = [-p[1] for p in allpts]
minx, maxx, miny, maxy = min(xs), max(xs), min(ys), max(ys)
s = min((W-2*PAD)/(maxx-minx), (H-2*PAD)/(maxy-miny))
ox = (W - (maxx-minx)*s)/2; oy = (H - (maxy-miny)*s)/2
def proj(p): return ((p[0]*k-minx)*s+ox, (-p[1]-miny)*s+oy)
def dp(pts, eps):
    if len(pts) < 3: return pts
    a, b = pts[0], pts[-1]; dmax, idx = 0, 0
    for i in range(1, len(pts)-1):
        p = pts[i]
        num = abs((b[1]-a[1])*p[0]-(b[0]-a[0])*p[1]+b[0]*a[1]-b[1]*a[0])
        den = math.hypot(b[0]-a[0], b[1]-a[1]) or 1e-9
        dd = num/den
        if dd > dmax: dmax, idx = dd, i
    if dmax > eps: return dp(pts[:idx+1], eps)[:-1] + dp(pts[idx:], eps)
    return [a, b]
res = []
for f in d['features']:
    name = f['properties']['district']
    parts, area_best, c_best = [], -1, (0,0)
    for r in rings(f['geometry']):
        Q = [proj(p) for p in r]; m = len(Q)//2
        P = dp(Q[:m+1], 0.6)[:-1] + dp(Q[m:], 0.6)
        if len(P) < 4: continue
        parts.append('M' + 'L'.join(f'{x:.1f},{y:.1f}' for x,y in P) + 'Z')
        A = 0; cx = cy = 0
        for i in range(len(P)-1):
            x0,y0 = P[i]; x1,y1 = P[i+1]; c = x0*y1-x1*y0
            A += c; cx += (x0+x1)*c; cy += (y0+y1)*c
        A /= 2
        if abs(A) > area_best and A != 0: area_best, c_best = abs(A), (cx/(6*A), cy/(6*A))
    slug = name.lower().replace(' ', '-')
    res.append({'id': slug, 'name': name, 'd': ''.join(parts), 'cx': round(c_best[0],1), 'cy': round(c_best[1],1)})
res.sort(key=lambda r: r['name'])
with open(out, 'w') as fh:
    fh.write('// Generated by scripts/build_geo.py from public district boundaries (simplified). Do not edit by hand.\n')
    fh.write(f'export const MAP_VIEWBOX = "0 0 {W} {H}";\n')
    fh.write('export interface DistrictShape { id: string; name: string; d: string; cx: number; cy: number }\n')
    fh.write('export const DISTRICT_SHAPES: DistrictShape[] = ' + json.dumps(res, indent=0) + ';\n')
print(len(res), sum(len(r['d']) for r in res))
